/**
 * intents.ts
 * Example phrasings for the embedding classifier, grouped by a *coarse* label.
 * The model only has to recognise the shape of the question; whether it is
 * about one site or everything, and most vs least, comes from slots.ts.
 * Site names and periods in these examples are masked at build time the same
 * way live questions are (see maskQuestion in slots.ts), so vary the wording,
 * not the entities.
 */

import type { Intent } from './tools';
import type { Slots } from './slots';

export const EMBED_LABELS = [
  'total_time',
  'avg_time',
  'visits',
  'rank',
  'daily_breakdown',
  'compare',
  'peak_time',
  'longest_session',
  'goal',
  'list_sites',
  'help',
  'out_of_scope',
] as const;

export type EmbedLabel = (typeof EMBED_LABELS)[number];

/** Refines a coarse label into the engine's intent using deterministic slots. */
export const labelToIntent = (label: EmbedLabel, slots: Slots): Intent => {
  const hasSite = Boolean(slots.site || slots.siteMention);
  switch (label) {
    case 'total_time':
      return hasSite ? 'site_total_time' : 'overall_total';
    case 'avg_time':
      return hasSite ? 'site_avg_time' : 'overall_avg';
    case 'visits':
      return hasSite ? 'site_visits' : 'overall_total';
    case 'rank':
      return slots.order === 'least' ? 'least_used' : 'most_used';
    default:
      return label;
  }
};

export const INTENT_EXAMPLES: Record<EmbedLabel, string[]> = {
  total_time: [
    'how much time did I spend on youtube today',
    'how long was I on github this week',
    'total time on reddit yesterday',
    'time spent on netflix in the last 7 days',
    'how many hours on twitter this month',
    'minutes on instagram today',
    'how long have I been on stack overflow',
    'my screen time on youtube',
    'usage of gmail this week',
    'how much of my day went to reddit',
    'did I spend a lot of time on facebook today',
    'total hours on chatgpt since monday',
    'what is my youtube time this week',
    'show my time on linkedin',
    'how much have I used discord lately',
    'total screen time today',
    'how much time did I spend online this week',
    'how long was I browsing yesterday',
    'my overall browser time in the last 7 days',
    'how many hours online this month',
    'total usage today',
    'how much have I browsed so far today',
    'screen time for the past 30 days',
    'how long have I been on the internet today',
    'overall time in chrome this week',
    'total minutes browsing yesterday',
    'my screen time since september 1',
    'how much screen time have I racked up',
    'what is my usage so far',
    'give me my total for the week',
    'how many hours did I burn on youtube',
    'time I put into github this week',
    'how much have I been on reddit',
    'my usage numbers for netflix',
    'tell me my screen time',
    'what does my youtube usage look like',
    'sum of my browsing time',
  ],
  avg_time: [
    'average screen time on youtube',
    'what is my avg daily time on github',
    'how long am I on reddit per day',
    'typical time I spend on instagram each day',
    'mean daily usage of netflix',
    'on average how many minutes a day on twitter',
    'how much do I usually spend on youtube in a day',
    'daily average for stack overflow this month',
    'normally how long am I on gmail every day',
    'what do I average on facebook daily',
    'roughly how long am I on discord each day',
    'per-day average on chatgpt',
    'average hours per day on netflix over the last 30 days',
    'what is my average daily screen time',
    'on average how many hours a day am I in the browser',
    'typical daily browsing time',
    'mean screen time per day this month',
    'how long do I usually browse each day',
    'daily average over the last 30 days',
    'average hours online per day',
    'what is a normal day of browsing for me',
    'average total time per day this week',
    'how much do I browse on an average day',
    'my usual daily usage',
    'per day average screen time',
    'what is my daily mean on youtube',
    'on a normal day how much github',
    'how much reddit do I do in a typical day',
    'average per day please',
    'what do I average',
    'my average daily figure for netflix',
    'how long per day on average',
  ],
  visits: [
    'how many times did I open youtube in the past 7 days',
    'how often do I visit github',
    'number of times I opened reddit today',
    'how many visits to instagram this week',
    'how frequently do I check twitter',
    'count of times I launched netflix this month',
    'how many tabs of stack overflow did I open',
    'did I open gmail a lot today',
    'how many times a day do I open facebook',
    'visits to chatgpt yesterday',
    'how often was linkedin opened this week',
    'how many sessions on discord',
    'times I went to youtube this week',
    'how many times did I check reddit yesterday',
    'how many tabs did I open today',
    'how many times did I open sites this week',
    'total number of visits today',
    'how many separate times was I on youtube',
    'count my github opens',
    'how many times have I gone back to reddit',
    'how often do I keep opening instagram',
    'visit count for netflix this week',
    'how many times did I load twitter',
    'number of opens today',
  ],
  rank: [
    'what is my most used site',
    'top 5 websites this week',
    'where do I spend the most time',
    'which site takes most of my time',
    'my top apps today',
    'which website do I open the most',
    'rank my sites by time',
    'biggest time sink this month',
    'most visited sites in the last 30 days',
    'what do I use the most',
    'which app is my favorite based on usage',
    'show me the ranking of my sites',
    'top three sites by opens',
    'what dominates my browsing',
    'most frequently opened website',
    'least used site this week',
    "what's the least used app",
    'which site do I barely use',
    'least opened website',
    'what do I use the least',
    'which site gets the least time',
    'my least visited sites this month',
    'bottom 3 sites by time',
    'which website do I rarely open',
    'sites I hardly touch',
    'smallest time on which site',
    'what gets ignored the most in my browsing',
    'least frequently opened site',
    'which of my sites has the lowest usage',
    'what takes up most of my browsing',
    'which site wins',
    'my number one time waster',
    'which is my number 1 site',
    'my top site by time',
    'the site ranked first for me',
    'which sites are at the top',
    'where does most of my time go',
    'what am I on most',
    'which site do I neglect',
    'what gets the smallest share of my time',
    'which sites are at the bottom',
    'what do I hardly ever open',
    'which site is my biggest habit',
    'order my sites by usage',
    'what consumes my screen time',
    'which site is gathering dust',
    'what do I hardly touch anymore',
    'which one do I forget about',
  ],
  daily_breakdown: [
    'which day was busiest this week',
    'show me a day by day breakdown',
    'usage trend for the last 30 days',
    'what day did I browse the most',
    'quietest day this week',
    'daily totals for the past 7 days',
    'how does my usage look each day',
    'graph of my screen time per day',
    'breakdown by day for youtube',
    'which day of the week am I online the most',
    'chart my browsing this month',
    'per-day numbers for reddit this week',
    'is my usage going up day by day',
    'what does each day look like',
    'on what day was I on youtube the longest',
    'give me every day separately',
    'show my totals for each day of the week',
    'which day had the least browsing',
    'plot my usage over the week',
    'my heaviest day this month',
    'my lightest day this week',
    'day-wise screen time',
    'how did each day go',
    'visualise my week',
  ],
  compare: [
    'compare this week vs last week',
    'did I use youtube more than yesterday',
    'is my screen time going up or down',
    'am I doing better than last week',
    'this month versus last month',
    'how does today compare to yesterday',
    'did I browse less this week',
    'more or less reddit than last week',
    'has my github usage increased',
    'difference between this week and last week',
    'am I improving compared to last month',
    'is my youtube time decreasing',
    'today vs last monday',
    'how much has my usage changed',
    'worse or better than last week',
    'was this a heavier week than the previous one',
    'has netflix gone down for me recently',
    'put this week next to last week',
    'has my browsing dropped off',
    'is my reddit time on the rise',
    'am I browsing more lately',
    'is my usage shrinking',
    'compare today with yesterday for github',
    'has anything changed compared to last week',
    'was last week better',
    'is my screen time rising',
  ],
  peak_time: [
    'when do I browse the most',
    'what time of day do I use youtube',
    'am I on reddit more in the morning or evening',
    'which hour am I most active',
    'peak time for my browsing',
    'when am I usually online',
    'do I use netflix late at night',
    'what hours do I spend on instagram',
    'when do I open twitter the most',
    'my busiest hour of the day',
    'hourly pattern of my screen time',
    'time of day I use the browser most',
    'when during the day am I on github',
    'am I a night browser or a morning browser',
    'at what hour am I browsing most',
    'do I use youtube mostly at night',
    'what part of the day am I most online',
    'when in the day do I use reddit the most',
    'my most active hour',
    'what time do I usually go on netflix',
    'when do I tend to browse',
    'is my usage mostly in the evening',
    'which hours am I on github',
    'usage by hour of the day',
  ],
  longest_session: [
    'longest session on youtube',
    'what was my longest single sitting this week',
    'longest stretch on reddit',
    'my longest continuous browsing session',
    'how long was my biggest netflix binge',
    'longest time in one go on github',
    'longest session without a break today',
    'what is the most time I spent on instagram in one session',
    'longest single visit to twitter',
    'my top 3 longest sessions this month',
    'biggest single session yesterday',
    'how long did my longest youtube session last',
    'what is the longest I stayed on reddit in one sitting',
    'my longest uninterrupted stretch this week',
    'longest continuous github session',
    'how long was my longest single netflix session',
    'the longest I have gone without leaving youtube',
    'marathon sessions this week',
    'longest run on one site',
    'my record session length',
  ],
  goal: [
    'did I stay under my goal this week',
    'how many days did I exceed my daily limit',
    'am I on track with my target',
    'did I meet my screen time goal today',
    'days over my limit this month',
    'how often did I go over budget',
    'am I within my daily goal',
    'how many days in a row under my goal',
    'did I hit my limit yesterday',
    'my streak of days under the goal',
    'was I over my target on monday',
    'which days did I break my limit',
    'am I keeping to my screen time goal',
    'did I go past my daily limit today',
    'how many days this week did I keep under my goal',
    'am I sticking to my target',
    'which days did I go over my allowance',
    'how long is my streak under the limit',
    'did I respect my limit',
    'goal check for this week',
    'how am I doing against my goal',
    'days I stayed within budget',
  ],
  list_sites: [
    'what sites did I use today',
    'list all websites I visited yesterday',
    'which apps did I open this week',
    'show me everything I browsed today',
    'what have I been on this week',
    'all the domains I visited',
    'which websites did I go to on monday',
    'list my sites for the last 7 days',
    'what did I use yesterday',
    'every site I opened this month',
    'show all pages I visited today',
    'what was I on today',
    'what websites did I visit',
    'name every site I opened',
    'which pages have I been on',
    'show me the list of sites',
    'where have I been today',
    'what did I browse',
    'all sites with usage this week',
    'give me the full list',
  ],
  help: [
    'what can you do',
    'help',
    'what can I ask you',
    'how does this work',
    'give me some examples',
    'what do you know about me',
    'what questions can I ask',
    'show me suggestions',
    'hello',
    'what are you able to answer',
    'how do I use this',
    'what kind of things can I ask',
  ],
  out_of_scope: [
    'how much did I use spotify app on my desktop',
    'how long was I on my phone',
    'time spent in vs code today',
    'how many hours did I play games',
    'my usage in firefox',
    'screen time on my android',
    'how long was excel open',
    'what apps did I use on windows',
    'total time on my laptop today',
    'how much time in the steam app',
    'usage outside the browser',
    'how long was I on my iphone',
    'time in microsoft word',
    'what did I do on my computer today',
    'how much time did I spend in illustrator',
    'screen time on my kindle',
    'how long did I play fortnite today',
    'usage of the teams desktop app',
    'how long was I in a video game',
    'time in the terminal',
    'how long was zoom running',
    'my ipad usage',
    'how much tv did I watch',
    'hours in the office app',
    'time on the playstation',
    'what is the weather today',
    'tell me a joke',
    'set a timer for 10 minutes',
    'block youtube for me',
  ],
};
